import type { Project } from '@/types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    clientName: 'The Millers',
    date: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    location: 'Central Park, NYC',
    photographer: 'Jane Doe',
    status: 'In Progress',
    stage: 'Editing',
    income: 1500,
    expenses: 200,
    paymentStatus: 'Partially Paid',
    description: 'Family portrait session for the Miller family. Golden hour shots requested.',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: '2',
    clientName: 'Bloomfield Corp',
    date: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    location: 'Downtown Office',
    photographer: 'John Smith',
    status: 'Complete',
    stage: 'Delivery',
    income: 3000,
    expenses: 550,
    paymentStatus: 'Paid',
    description: 'Corporate headshots for the executive team. 10 members.',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: '3',
    clientName: 'Alice & Bob',
    date: new Date(new Date().setDate(new Date().getDate() + 20)).toISOString(),
    location: 'Sunset Cliffs',
    photographer: 'Jane Doe',
    status: 'Backlog',
    stage: 'Shooting',
    income: 2200,
    expenses: 300,
    paymentStatus: 'Unpaid',
    description: 'Wedding ceremony and reception. Full day event.',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: '4',
    clientName: 'Startup Inc.',
    date: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
    location: 'Co-working Space',
    photographer: 'Emily White',
    status: 'In Progress',
    stage: 'Shooting',
    income: 1200,
    expenses: 150,
    paymentStatus: 'Paid',
    description: 'Product launch event photography.',
    imageUrl: 'https://placehold.co/600x400.png',
  },
    {
    id: '5',
    clientName: 'The Davidsons',
    date: new Date(new Date().setDate(new Date().getDate() + 15)).toISOString(),
    location: 'Their Residence',
    photographer: 'John Smith',
    status: 'Backlog',
    stage: 'Shooting',
    income: 800,
    expenses: 50,
    paymentStatus: 'Unpaid',
    description: 'Newborn baby photoshoot at home.',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: '6',
    clientName: 'Local Restaurant',
    date: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    location: 'The Grand Bistro',
    photographer: 'Jane Doe',
    status: 'In Progress',
    stage: 'Editing',
    income: 1800,
    expenses: 250,
    paymentStatus: 'Partially Paid',
    description: 'Food photography for new menu items. 15 dishes.',
    imageUrl: 'https://placehold.co/600x400.png',
  },
];
