import type { Project } from '@/types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    clientName: 'Casamento dos Sonhos',
    date: '2024-08-15T10:00:00.000Z',
    location: 'Buffet La Luna, São Paulo',
    photographer: 'Ana Costa',
    status: 'Em Andamento',
    stage: 'Edição',
    income: 5000,
    expenses: 800,
    paymentStatus: 'Parcialmente Pago',
    description: 'Cobertura completa do casamento de Joana e Pedro, incluindo cerimônia, recepção e ensaio pré-casamento.',
    imageUrl: 'https://placehold.co/600x400.png',
    galleryImages: [],
  },
  {
    id: 'proj-2',
    clientName: 'Ensaio Família Silva',
    date: '2024-07-20T14:00:00.000Z',
    location: 'Parque Ibirapuera, São Paulo',
    photographer: 'Marcos Rocha',
    status: 'Concluído',
    stage: 'Entrega',
    income: 1200,
    expenses: 150,
    paymentStatus: 'Pago',
    description: 'Ensaio fotográfico ao ar livre com a família Silva para celebrar o aniversário de 5 anos do filho Lucas.',
    imageUrl: 'https://placehold.co/600x400.png',
    galleryImages: [],
  },
  {
    id: 'proj-3',
    clientName: 'Fotos Corporativas TechInc',
    date: '2024-09-01T09:00:00.000Z',
    location: 'Escritório TechInc, Av. Faria Lima',
    photographer: 'Ana Costa',
    status: 'Pendente',
    stage: 'Sessão Fotográfica',
    income: 2500,
    expenses: 300,
    paymentStatus: 'Não Pago',
    description: 'Fotos de retrato dos executivos e do ambiente de trabalho para o novo site da empresa.',
    imageUrl: 'https://placehold.co/600x400.png',
    galleryImages: [],
  }
];
